import type { NextPage } from "next";
import Head from "next/head";
import EducationCard from "../components/EducationCard";
import WorkExperienceCard from "../components/WorkExperinceCard";
import styles from "../styles/Home.module.css";

const WORK_EXPERIENCE = [
  {
    position: "Desarrollador web",
    companyName: "VOTH SOLUTIONS",
    city: "Saltillo",
    start: "Julio 2019",
    end: "Presente",
    tasks: [
      "Encargado de los proyectos que impliquen el desarrollo web (JS).",
      "Desarrollé un ERP (con React y Node) y otros sistemas web para diversos clientes.",
    ],
  },
  {
    position: "Desarrollador de software",
    companyName: "A&T SORT COMPANY",
    city: "Saltillo",
    start: "2018",
    end: "2019",
    tasks: [
      "Mantenimiento y creación de nuevos módulos para su sistema interno (ERP) hecho con PHP.",
      "Formé parte del comienzo de su nuevo sistema y desarrollé su aplicación móvil usando React Native.",
    ],
  },
  {
    position: "Programador web",
    companyName: 'GESO "PÁGINAS WEB"',
    city: "Remoto",
    start: "2018",
    end: "2019",
    tasks: [
      "Encargado de desarrollar varias páginas web para clientes de dicha empresa.",
    ],
  },
  {
    position: "Programador freelancer",
    start: "2015",
    end: "2018",
    tasks: [
      "Realicé desde páginas web y programas simples hasta sistemas más elaborados, programados en Java, C#, C++, Visual Basic .Net y PHP",
    ],
  },
];

const EDUCATION = [
  {
    school:
      "Ingeniero en Sistemas Computacionales, Instituto Tecnológico de Saltillo",
    start: "Agosto 2014",
    end: "Junio 2019",
  },
  {
    school:
      "Técnico en informática, Centro de Estudios Tecnológicos, Industriales y de Servicio #48",
    start: "Agosto 201",
    end: "Junio 2014",
  },
];

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Curriculum vitae</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.leftSection}>
          <div className={styles.info}>
            <h2 className={styles.titleName}>
              Diego Ivan
              <br />
              Padilla Bernal
            </h2>
            <div className={styles.divider} style={{ width: 100 }} />
            <p className={styles.specialist}>Fullstack Javascript Developer</p>
          </div>
          <div className={styles.personalData}>
            <h3>Datos personales</h3>
            <p>
              <b>Ubicación:</b>
              <br />
              Saltillo, Coahuila, México
            </p>
            <p>
              <b>Teléfono:</b>
              <br />
              8442220828
            </p>
            <p>
              <b>Correo electrónico:</b>
              <br />
              <a href="mailto:diego.bernal17@gmail.com">
                diego.bernal17@gmail.com
              </a>
            </p>
            <p>
              <b>Fecha de nacimiento:</b>
              <br />
              17-01-1996
            </p>
          </div>
          <div className={styles.divider} />
          <div className={styles.links}>
            <h3>Links</h3>
            <a
              href="https://linkedin.com/in/diegopbernal/"
              target="_blank"
              rel="noreferrer"
            >
              Linkedin
            </a>
            <a
              href="https://platzi.com/p/diego-p-bernal/"
              target="_blank"
              rel="noreferrer"
            >
              Platzi
            </a>
            <a
              href="https://github.com/DiegoBernal17"
              target="_blank"
              rel="noreferrer"
            >
              Github
            </a>
          </div>
          <div className={styles.divider} />
          <div className={styles.proficiencies}>
            <h3>Competencias</h3>
            <ul>
              <li>Organización</li>
              <li>Proactividad</li>
              <li>Responsabilidad</li>
              <li>Resolución de problemas</li>
              <li>Trabajo en equipo</li>
              <li>Aprendizaje independiente</li>
            </ul>
          </div>
          <div className={styles.divider} />
          <div className={styles.languages}>
            <h3>Idiomas</h3>
            <p>
              Español: <b>Nativo</b>
            </p>
            <p>
              Inglés: <b>B1</b>
            </p>
          </div>
        </div>

        <div className={styles.rightSection}>
          <div className={styles.professionalProfile}>
            <h2 className={styles.title}>Perfil profesional</h2>
            <p>
              Entusiasta de la tecnología, la programación y de aprender algo
              nuevo cada día. Con más de 4 años usando Javascript y programando
              desde temprana edad. Buscando mejorar mis habilidades como
              programador y como persona.
            </p>
          </div>
          <div className={styles.workExperience}>
            <h2 className={styles.title}>Experiencia laboral</h2>
            {WORK_EXPERIENCE.map((workExp, i) => (
              <WorkExperienceCard
                key={i}
                position={workExp.position}
                companyName={workExp.companyName}
                city={workExp.city}
                start={workExp.start}
                end={workExp.end}
                tasks={workExp.tasks}
              />
            ))}
          </div>
          <div className={styles.education}>
            <h2 className={styles.title}>Formación</h2>
            {EDUCATION.map((education, i) => (
              <EducationCard
                key={i}
                school={education.school}
                start={education.start}
                end={education.end}
              />
            ))}
          </div>
          <div className={styles.skills}>
            <h2 className={styles.title}>Habilidades técnicas</h2>
            <ul>
              <li>
                <b>Frontend:</b> HTML, CSS, Javascript, React, NextJS
              </li>
              <li>
                <b>Backend:</b> NodeJS, Express, NestJS, GraphQL
              </li>
              <li>
                <b>Base de datos:</b> MariaDB, MongoDB, Firebase
              </li>
              <li>Entre otras tecnologías más.</li>
            </ul>
          </div>
          <div className={styles.participations}>
            <h2 className={styles.title}>Participaciones y asistencias</h2>
            <p>
              Concursos de programación y de redes. Cursos en linea, congresos,
              pláticas, Talent land y hackatons.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
